services:
  ros2-server:
    build:
      dockerfile: toxic_server/Dockerfile
    command: bash -c "cd ~/ros2/toxic_server && \
                      source install/setup.bash && \
                      ros2 launch src/toxic_server/launch/toxic_launch.py"

  ros2-client:
    environment:
      - YAML=${YAML}
    build:
      dockerfile: toxic_clients/Dockerfile
    command: bash -c "cd ~/ros2/toxic_clients && \
                      source install/setup.bash && \
                      ros2 launch src/toxic_clients/launch/toxic_launch.py custom_way:=${YAML}"

  ros2-bag-recorder:
    build:
      dockerfile: toxic_clients/Dockerfile
    command: bash -c "cd ~/ros2/toxic_clients && \
                      source install/setup.bash && \
                      ros2 bag record --storage sqlite3 --topics /relationship_logs -o /shared/new_logs"
    volumes:
      - ./shared:/shared
