services:
  ros2-server:
    environment:
      - YAML=${YAML}
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd ~/ros2/ros2-learn &&
                  git pull origin main &&
                  rm -rf build/ install/ log/ &&
                  colcon build --packages-select py_pubsub toxic_relationship &&
                  source install/setup.bash &&
                  cd src/py_pubsub/launch &&
                  ros2 launch toxic_launch.py  custom_way:=${YAML}"
